### PR TITLE
feat: ui for new sample app with apns

### PR DESCRIPTION
**Pull request by ami-aman**
Related PR https://github.com/customerio/issues/issues/9679 ( This PR does not close the ticket)
This PR only has the UI components of the new sample app (Ami app iOS APNS)

- Login
- Dashboard
- Custom Attributes Screen

Pending Screens
- Settings screen - for which I will open a separate PR .

To keep the PRs small & reviewable, I have opened this PR with only UI updates. Logic & functional implementation to be done in a separate PR.

Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
- [ ] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request. 
- [ ] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1). 
- [ ] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After code reviews are approved and you determine this PR is ready to merge, select *Squash and Merge* button on this screen, leave the title and description to the default values, then merge the PR.

### CODE REVIEW

**Review by levibostian — COMMENTED** [review]
All of the source code changes made look good to me. Two concerns I have: 

1. I noticed the .xcodeproj was re-created? Or was it just moved? I understand if the project file needs modified, but not re-created or moved locations. Is there a reason that this was needed? 

2. The file structure was modified from: 
```
APN-UIKit/
  Sources/
  APN UIKit.xcodeproj
```

to:
```
APN-UIKit/
  APN UIKit/
    APN UIKit/ <-- sources
    APN UIKit.xcodeproj
```

This file structure seems verbose and overly complicated to navigate to me compare to how it was. Are you opposed to reverting back to the old file structure?

**Comment by ami-aman** [comment]
Thanks for the review, Levi.

1. I re-created . xcodeproj because it was missing many important files like .plist, window in AppDelegate etc. I spent quite sometime adding those files/code and fixing the errors but then I realised that it would be quick to re-create the project than fixing the existing structure. Though, this does not make any difference in the folder structure

2. The folder structure is [same as it is in iOS repository](https://github.com/customerio/customerio-ios/tree/main/Apps/APN-UIKit).

**Review by levibostian — CHANGES_REQUESTED** [review]
I would prefer to not re-create the Xcode project since I modified it to allow installing the local copy of the SDK and not a remote copy. Re-creating the Xcode project in this PR would mean me having to do that work over again after merging this PR. 

Also, I would prefer we did not modify the Xcode project to include files such as `Info.plist`. Since Xcode 13 removed the need for Info.plist files, I prefer we use this modern approach.  

Also because the file structure was modified in this PR, I am going to reject the PR at this time and ask if we can revert back to using the existing file structure and existing Xcode project? 

It might be easier to close this PR and make the source code changes that this PR introduced into a new PR, or, revert some commits in this PR and keep this PR open. I am open to whatever is easiest.

**Comment by ami-aman** [comment]
Levi, I have reached quite far now in terms of completion. I would request you to re-consider this PR as it would be quite a lot of effort for me now to redo everything be it cherry pick. Which file structure according to you, you think is modified ?

> I modified it to allow installing the local copy of the SDK and not a remote copy
I assume this is a small change and can be done easily. If you are concerned about it then I can make this change. Not a deal!

**Review by levibostian — APPROVED** [review]
After merging this PR, some changes will need to be done to the app's file system and Xcode project. But, that would be more difficult to do at this time with multiple PRs being open. 

I suggest we merge this PR as-is, finish up the development work for the APN app, then make a final PR with the changes required to get the app building on CI.

**Pull request merged**
