### PR TITLE
fix: rename in-app listener keys

### PR DESCRIPTION
**Pull request by Shahroz16**
closes: https://github.com/customerio/issues/issues/9189

Complete each step to get your pull request merged in. [Learn more about the workflow this project uses](https://github.com/customerio/customerio-ios/blob/develop/docs/dev-notes/GIT-WORKFLOW.md). 
- [ ] [Assign members of your team](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/requesting-a-pull-request-review) to review the pull request. 
- [ ] Wait for pull request status checks to complete. If there are problems, fix them until you see that [all status checks are passing](https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fsymfony.com%2Fdoc%2F4.3%2F_images%2Fdocs-pull-request-symfonycloud.png&f=1&nofb=1). 
- [ ] Wait until the pull request has been reviewed *and approved* by a teammate
- [ ] After pull request is approved, and you determine it's ready **add the label "Ready to merge"** to the pull request. A bot will *squash and merge* the pull request for you after the label is added.

### CODE REVIEW

**Comment by Shahroz16** [comment]
This PR has the latest code from develop too.

**Review by levibostian — CHANGES_REQUESTED** [review]
If you could, please, not include changes from `develop`. I am nervous to merge this in and mess something up compared to:

* this PR only being renaming of keys, merge this. 
* update `levi/gist-event-listeners` with `develop` since, it's base is `develop` the "Files changed" tab on that PR would not include what's already in `develop` when this PR shows all of those changes.

**Comment by levibostian** [comment]
I appreciate this PR! Thanks for trying to help by doing this work. 

Since I am working on `levi/gist-event-listeners` right now and plan to merge it in just a few minutes, I'll close this PR and do a commit myself into that branch. Since this PR requires more work - by viewing my code review comment.

**Comment by Shahroz16** [comment]
Appreciate the response but I believe `develop` has been merged into`levi/gist-event-listeners`, so if you just pulled the latest from the `levi/gist-event-listeners` into this, you would have just seen the changes pertaining to renaming keys in the `Files changed`. 

But as long as the work gets done, in your other branch, it's all good.

**Pull request closed without merging**
